[profile.default]
src = 'src'
out = 'out'
libs = ['lib']  # See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = ['ds-test=lib/ds-test/', 'forge-std/=lib/forge-std/']
